## 1. Import Dependencies

In [1]:
# # DEV ZONE

# #auto reload libs
# %load_ext autoreload
# %autoreload 2

# # you may also wish to see the logs (parallelise logs include link to Dask cluster dashboard)
# import logging
# logging.basicConfig(level=logging.INFO)

In [1]:
import os

# Resolves a conflict in Geopandas. Improves speed. Slower otherwise.
os.environ["USE_PYGEOS"] = "0"

In [2]:
from mosaiks import get_features

## 2. Import test data
In this case, we are creating random GPS coordinates

In [3]:
# Example: Select 5 coordinates in Uttar Pradesh, India
lats = [26.51268717, 26.55187804, 26.54949092, 26.54105597, 26.54843896]
lons = [80.51489844, 80.54864309, 80.57813289, 80.51412136, 80.52254959]

## 3. Execute a default run of the `get_features` function

In [4]:
df_featurised = get_features(
    lats,
    lons,
    datetime="2017", # or ["2013-01-1-01", "2018-01-06"] or ...
    image_width=3000,
)

df_featurised

WARNING:root:Skipping 0: 'proj:epsg'
WARNING:root:Skipping 1: 'proj:epsg'
WARNING:root:Skipping 2: 'proj:epsg'
WARNING:root:Skipping 3: 'proj:epsg'
WARNING:root:Skipping 4: 'proj:epsg'

,mosaiks_0,mosaiks_1,mosaiks_2,mosaiks_3,mosaiks_4,mosaiks_5,mosaiks_6,mosaiks_7,mosaiks_8,mosaiks_9,...,mosaiks_3991,mosaiks_3992,mosaiks_3993,mosaiks_3994,mosaiks_3995,mosaiks_3996,mosaiks_3997,mosaiks_3998,mosaiks_3999,stac_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."

## 4. Run `get_features` with Dask parallelization

To run the code with the built-in Dask parallelization, set `parallelize` to `True` and `dask_chunksize` to a suitable integer given the size of your dataset.

In [5]:
df_featurised = get_features(
    lats,
    lons,
    datetime="2017", # or ["2013-01-1-01", "2018-01-06"] or ...
    image_width=3000,
    parallelize=True,
    dask_chunksize=2, # set this to 200+ to see benefits from parallization
)

df_featurised

WARNING:root:Skipping 0: 'proj:epsg'
WARNING:root:Skipping 1: 'proj:epsg'
WARNING:root:Skipping 0: 'proj:epsg'
WARNING:root:Skipping 0: 'proj:epsg'
WARNING:root:Skipping 1: 'proj:epsg'

,mosaiks_0,mosaiks_1,mosaiks_2,mosaiks_3,mosaiks_4,mosaiks_5,mosaiks_6,mosaiks_7,mosaiks_8,mosaiks_9,...,mosaiks_3991,mosaiks_3992,mosaiks_3993,mosaiks_3994,mosaiks_3995,mosaiks_3996,mosaiks_3997,mosaiks_3998,mosaiks_3999,stac_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[LC08_L2SP_144042_20171017_02_T1, LC08_L2SP_14..."